# Generated by Django 2.0.1 on 2018-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_auto_20180325_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
