# Generated by Django 2.0.1 on 2018-04-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_auto_20180325_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sroll',
            field=models.IntegerField(default=0),
        ),
    ]
