# Generated by Django 2.0.1 on 2018-04-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_student_sroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='syear',
            field=models.CharField(default='', max_length=500),
        ),
    ]
