# Generated by Django 2.0.1 on 2018-04-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_student_syear'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='extmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='intmarks',
            field=models.IntegerField(default=0),
        ),
    ]
