# Generated by Django 2.0.1 on 2018-04-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_auto_20180429_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('marksid', models.AutoField(primary_key=True, serialize=False)),
                ('intmarks', models.IntegerField(default=0)),
                ('extmarks', models.IntegerField(default=0)),
                ('msstudentid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='faculty.staffs')),
                ('msubjectid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='faculty.subject')),
            ],
        ),
    ]
