# Generated by Django 2.0.1 on 2018-03-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_remove_faculty_fsubjectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='fbranchid',
        ),
    ]
