# Generated by Django 2.0.1 on 2018-03-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_remove_faculty_fbranchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fbranchid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='faculty.branch'),
        ),
    ]
